# HTTP Server
server:
  port: 8080
  context-path: /
# Spring properties
spring:
  resources:
    static-locations: file:${custom.fileServer.rootFolder}
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://svn.softvan.com.cn:5011/new-frame?serverTimezone=UTC&noAccessToProcedureBodies=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8
    username: root
    password: root
    #    # 下面为连接池的补充设置，应用到上面所有数据源中
    #    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 300000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 600000
    #validationQuery: select "1"
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: "druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000"
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  #redis配置
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    password: admin123
  http:
    encoding:
      force: true
      charset: UTF-8


logging:
  config: classpath:logback.xml
#mybatis配置
mybatis:
  #实体依赖路径
  type-aliases-package: cn.com.softvan.model
  #mybatis映射文件路径
  mapper-locations: classpath*:mybatis/**/*.xml
mapper:
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

custom:
  permitUrlPattern: /upload,/proxy,/m,/auth
  serverPath: 127.0.0.1:8080
  fileServer:
    rootFolder: /home/lyzhpt/file/
    upload: ${custom.fileServer.rootFolder}upload/
    download: /upload/
    image:
      executorServiceSize: 5
      n0:
        width: 200
        height: 200
      n1:
        width: 400
        height: 400
      n2:
        width: 800
        height: 800
      n3:
        width: 1200
        height: 1200
